# Generated by Django 4.1.5 on 2023-03-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.home')),
            ],
        ),
    ]
