# Generated by Django 4.1.5 on 2023-01-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
