# Generated by Django 4.1.5 on 2023-01-23 01:30

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_home_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='banner',
            field=models.ImageField(null=True, upload_to=home.models.custom_upload_to),
        ),
    ]
