# Generated by Django 4.1.5 on 2023-01-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_home_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='banner',
            field=models.ImageField(null=True, upload_to='2023-01-23 01:32:13.662238.png'),
        ),
    ]
