# Generated by Django 4.1.5 on 2023-01-23 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_home_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='banner',
            field=models.ImageField(null=True, upload_to=datetime.datetime(2023, 1, 23, 1, 50, 8, 270585)),
        ),
    ]
