# Generated by Django 4.1.5 on 2023-02-15 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_home_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='banner',
            field=models.ImageField(null=True, upload_to=datetime.datetime(2023, 2, 15, 14, 23, 0, 57867)),
        ),
    ]
