# Generated by Django 4.1.5 on 2023-02-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=10)),
                ('b', models.CharField(max_length=10)),
                ('c', models.CharField(max_length=10)),
                ('d', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('grade', models.PositiveIntegerField()),
                ('group', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopFake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_name', models.CharField(max_length=30)),
                ('no_fruits', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopFake2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok_name', models.IntegerField()),
                ('ok_fruits', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fruits', models.ManyToManyField(to='fruits.fruits')),
            ],
        ),
    ]
