# Generated by Django 4.1.5 on 2023-01-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_fruits_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruits',
            name='group',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
