# Generated by Django 4.1.5 on 2023-01-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0004_shops'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_name', models.CharField(max_length=30)),
                ('no_fruits', models.ManyToManyField(to='fruits.fruits')),
            ],
        ),
    ]
