# Generated by Django 4.1.5 on 2023-01-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0005_shopfake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopfake',
            name='no_fruits',
        ),
        migrations.AddField(
            model_name='shopfake',
            name='no_fruits',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
