# Generated by Django 4.1.5 on 2023-01-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0006_remove_shopfake_no_fruits_shopfake_no_fruits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFake2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok_name', models.IntegerField()),
                ('ok_fruits', models.TextField()),
            ],
        ),
    ]
